### ISSUE TITLE
Crash on Arch Linux

### ISSUE THREAD

**Issue by theGeekPirate** [gdm85/wolfengo#2]
Commenting out the panic on line 67 of main.go allows the application to run normally.

```
./bin/wolfengo 
WolfenGo v0.1.0, Copyright (C) 2016 gdm85
https://github.com/gdm85/wolfengo
WolfenGo comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under GNU/GPLv2 license.
4.5.0 NVIDIA 358.16
panic: [GL_DEBUG] source 33350 gltype 33361 id 131185 severity 33387 length 164: Buffer detailed info: Buffer object 1 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.


goroutine 1 [running, locked to thread]:
main.debugCb(0x825100008246, 0x826b00020071, 0xa4, 0xc8200142c0, 0xa4, 0x0)
        /mnt/btrfs/Programming/Go/src/github.com/gdm85/wolfengo/src/main.go:67 +0x348
github.com/go-gl/gl/v2.1/gl.glowDebugCallback_gl21(0x825100008246, 0x826b00020071, 0x7f47000000a4, 0x7f4778e6b400, 0x0)
        /mnt/btrfs/Programming/Go/src/github.com/gdm85/wolfengo/.gopath/src/github.com/go-gl/gl/v2.1/gl/debug.go:29 +0x8e
github.com/go-gl/gl/v2.1/gl._Cfunc_glowBufferData(0x7f477ab8be80, 0x8892, 0x80, 0xc82008e080, 0x88e4)
        github.com/go-gl/gl/v2.1/gl/_obj/_cgo_gotypes.go:7307 +0x35
github.com/go-gl/gl/v2.1/gl.BufferData(0x8892, 0x80, 0xc82008e080, 0x88e4)
        /mnt/btrfs/Programming/Go/src/github.com/gdm85/wolfengo/.gopath/src/github.com/go-gl/gl/v2.1/gl/package.go:18265 +0x47
main.(*Mesh).addVertices(0xc82043f650, 0xc8204f9db0, 0x4, 0x4, 0xc82000e200, 0x6, 0x6, 0xc800000000)
        /mnt/btrfs/Programming/Go/src/github.com/gdm85/wolfengo/src/mesh.go:53 +0x197
main.NewMesh(0xc8204f9db0, 0x4, 0x4, 0xc82000e200, 0x6, 0x6, 0x496600, 0x0, 0x0)
        /mnt/btrfs/Programming/Go/src/github.com/gdm85/wolfengo/src/mesh.go:30 +0xb1
main.(*Object).initMedkit(0xb9f0a0, 0x0, 0x0)
        /mnt/btrfs/Programming/Go/src/github.com/gdm85/wolfengo/src/medkit.go:51 +0x404
main.main()
        /mnt/btrfs/Programming/Go/src/github.com/gdm85/wolfengo/src/main.go:129 +0x4b2

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1
```

**Comment by theGeekPirate** [comment]
I should have read the code a bit, as that was simply due to debug being enabled.

Setting `debugGL        = false` on line 34 of main.go prevents the crash.

**Comment by gdm85** [comment]
I see what's the problem here. I am using `panic` also for a severity that doesn't deserve it. Your warning happens with `4.5.0 NVIDIA 358.16` but not with mine which is `3.0 Mesa 10.1.3`. I am going to fix this.
